import { Organization, User, Resource, Booking, ApprovalRequest, AppNotification } from '../src/types';

export const initialOrganization: Organization = {
  id: 'org-spacesync-hq',
  name: 'SpaceSync Technologies',
  industry: 'Technology & Software',
  timezone: '(GMT-08:00) Pacific Time',
  currency: 'USD ($)',
  businessHours: [
    { day: 'Monday', enabled: true, startTime: '09:00 AM', endTime: '06:00 PM' },
    { day: 'Tuesday', enabled: true, startTime: '09:00 AM', endTime: '06:00 PM' },
    { day: 'Wednesday', enabled: true, startTime: '09:00 AM', endTime: '06:00 PM' },
    { day: 'Thursday', enabled: true, startTime: '09:00 AM', endTime: '06:00 PM' },
    { day: 'Friday', enabled: true, startTime: '09:00 AM', endTime: '05:00 PM' },
    { day: 'Saturday', enabled: false, startTime: '09:00 AM', endTime: '05:00 PM' },
    { day: 'Sunday', enabled: false, startTime: '09:00 AM', endTime: '05:00 PM' },
  ],
  createdAt: new Date().toISOString(),
};

export const initialUsers: User[] = [
  {
    id: 'usr-1',
    orgId: 'org-spacesync-hq',
    email: 'alex.chen@spacesync.io',
    name: 'Alex Chen',
    role: 'super_admin',
    department: 'Operations',
    jobTitle: 'Global Administrative Lead',
    phone: '+1 (555) 902-1234',
    accessGroup: 'Global-Cloud-Arch',
    status: 'active',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    lastLogin: 'Just now',
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'usr-2',
    orgId: 'org-spacesync-hq',
    email: 's.jenkins@spacesync.io',
    name: 'Sarah Jenkins',
    role: 'space_admin',
    department: 'Marketing',
    jobTitle: 'Facilities & Ops Lead',
    phone: '+1 (555) 432-8765',
    accessGroup: 'Product-Strategy',
    status: 'active',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    lastLogin: '2 mins ago',
    createdAt: new Date(Date.now() - 25 * 86400000).toISOString(),
  },
  {
    id: 'usr-3',
    orgId: 'org-spacesync-hq',
    email: 'm.thorne@spacesync.io',
    name: 'Marcus Thorne',
    role: 'member',
    department: 'Engineering',
    jobTitle: 'Principal Engineer',
    phone: '+1 (555) 888-2341',
    accessGroup: 'Global-Cloud-Arch',
    status: 'active',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    lastLogin: '2 mins ago',
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
  {
    id: 'usr-4',
    orgId: 'org-spacesync-hq',
    email: 'e.rod@spacesync.io',
    name: 'Elena Rodriguez',
    role: 'member',
    department: 'Design',
    jobTitle: 'UX Lead',
    phone: '+1 (555) 234-5678',
    accessGroup: 'Product-Strategy',
    status: 'active',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    lastLogin: '4 hours ago',
    createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
  {
    id: 'usr-5',
    orgId: 'org-spacesync-hq',
    email: 'j.vance@spacesync.io',
    name: 'Julian Vance',
    role: 'member',
    department: 'Legal',
    jobTitle: 'Contract Manager',
    phone: '+1 (555) 345-6789',
    accessGroup: 'Corporate-Compliance',
    status: 'inactive',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    lastLogin: '3 days ago',
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: 'usr-6',
    orgId: 'org-spacesync-hq',
    email: 'a.chen@spacesync.io',
    name: 'Aria Chen',
    role: 'member',
    department: 'Operations',
    jobTitle: 'Logistics Coordinator',
    phone: '+1 (555) 765-4321',
    accessGroup: 'Fleet-Ops',
    status: 'active',
    avatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
    lastLogin: 'Just now',
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
];

export const initialResources: Resource[] = [
  {
    id: 'res-1',
    orgId: 'org-spacesync-hq',
    name: 'Meeting Room Alpha',
    type: 'room',
    building: 'Tower A, 4th Floor',
    floorLocation: '4th Floor, Suite 402',
    capacity: 12,
    photo: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&auto=format&fit=crop&q=80',
    amenities: ['projector', 'whiteboard', 'video-conf', 'power-outlets'],
    accessGroup: 'All Staff',
    status: 'available',
    requiresApproval: false,
    bufferMinutes: 10,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-2',
    orgId: 'org-spacesync-hq',
    name: 'Bio-Chem Lab 02',
    type: 'equipment',
    building: 'Res. Park, Bld C',
    floorLocation: 'Ground Floor Lab B',
    capacity: 6,
    photo: 'https://images.unsplash.com/photo-1581093458791-9f3c3900df4b?w=600&auto=format&fit=crop&q=80',
    amenities: ['whiteboard', 'power-outlets'],
    accessGroup: 'R&D Team',
    status: 'maintenance',
    requiresApproval: true,
    bufferMinutes: 15,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-3',
    orgId: 'org-spacesync-hq',
    name: 'Focus Pod 12',
    type: 'desk',
    building: 'North Hub, L2',
    floorLocation: 'Level 2 Quiet Zone',
    capacity: 1,
    photo: 'https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?w=600&auto=format&fit=crop&q=80',
    amenities: ['monitors', 'power-outlets'],
    accessGroup: 'Open Access',
    status: 'available',
    requiresApproval: false,
    bufferMinutes: 5,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-4',
    orgId: 'org-spacesync-hq',
    name: 'The Auditorium',
    type: 'room',
    building: 'Tower A, Lobby',
    floorLocation: 'Ground Floor Main Hall',
    capacity: 150,
    photo: 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=600&auto=format&fit=crop&q=80',
    amenities: ['projector', 'whiteboard', 'av-system', 'video-conf'],
    accessGroup: 'Management',
    status: 'available',
    requiresApproval: true,
    bufferMinutes: 30,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-5',
    orgId: 'org-spacesync-hq',
    name: 'Grand Hall A',
    type: 'room',
    building: 'Conference Center',
    floorLocation: '1st Floor East Wing',
    capacity: 80,
    photo: 'https://images.unsplash.com/photo-1542744836-5505233576f3?w=600&auto=format&fit=crop&q=80',
    amenities: ['projector', 'av-system', 'video-conf'],
    accessGroup: 'All Staff',
    status: 'available',
    requiresApproval: false,
    bufferMinutes: 15,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-6',
    orgId: 'org-spacesync-hq',
    name: 'Creative Studio 2',
    type: 'room',
    building: 'Design Wing',
    floorLocation: '3rd Floor',
    capacity: 10,
    photo: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=600&auto=format&fit=crop&q=80',
    amenities: ['whiteboard', 'monitors', 'video-conf'],
    accessGroup: 'Product-Strategy',
    status: 'available',
    requiresApproval: false,
    bufferMinutes: 10,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-7',
    orgId: 'org-spacesync-hq',
    name: 'Podcast Booth 1',
    type: 'equipment',
    building: 'Media Suite',
    floorLocation: '2nd Floor Sound Lab',
    capacity: 4,
    photo: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=600&auto=format&fit=crop&q=80',
    amenities: ['av-system', 'power-outlets'],
    accessGroup: 'Open Access',
    status: 'available',
    requiresApproval: false,
    bufferMinutes: 10,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'res-8',
    orgId: 'org-spacesync-hq',
    name: 'Quiet Zone C',
    type: 'desk',
    building: 'East Wing Basement',
    floorLocation: 'B1 Workstation 14',
    capacity: 1,
    photo: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=600&auto=format&fit=crop&q=80',
    amenities: ['monitors', 'power-outlets'],
    accessGroup: 'Open Access',
    status: 'available',
    requiresApproval: false,
    bufferMinutes: 5,
    createdAt: new Date().toISOString(),
  },
];

// Generate today ISO date strings
const now = new Date();
const todayStr = now.toISOString().split('T')[0];

export const initialBookings: Booking[] = [
  {
    id: 'bk-1',
    orgId: 'org-spacesync-hq',
    resourceId: 'res-1',
    resourceName: 'Studio A-12',
    resourceType: 'room',
    building: 'Tower A, 4th Floor',
    requesterId: 'usr-3',
    requesterName: 'Jordan Smith',
    requesterEmail: 'jordan.smith@spacesync.io',
    department: 'Engineering',
    title: 'Architecture Review & Sprint Sync',
    startTime: `${todayStr}T14:00:00.000Z`,
    endTime: `${todayStr}T15:30:00.000Z`,
    attendeesCount: 8,
    notes: 'Projector and AV setup needed',
    status: 'confirmed',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'bk-2',
    orgId: 'org-spacesync-hq',
    resourceId: 'res-3',
    resourceName: 'Desk #092',
    resourceType: 'desk',
    building: 'North Hub, L2',
    requesterId: 'usr-4',
    requesterName: 'Maria Garcia',
    requesterEmail: 'm.garcia@spacesync.io',
    department: 'Product Design',
    title: 'UX Focus Work',
    startTime: `${todayStr}T09:00:00.000Z`,
    endTime: `${todayStr}T18:00:00.000Z`,
    attendeesCount: 1,
    status: 'pending',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'bk-3',
    orgId: 'org-spacesync-hq',
    resourceId: 'res-1',
    resourceName: 'Zoom Room 4',
    resourceType: 'room',
    building: 'Tower A, 4th Floor',
    requesterId: 'usr-5',
    requesterName: 'Kenji Yamamoto',
    requesterEmail: 'k.yamamoto@spacesync.io',
    department: 'Sales',
    title: 'Enterprise Client Demo Call',
    startTime: `${todayStr}T11:30:00.000Z`,
    endTime: `${todayStr}T12:00:00.000Z`,
    attendeesCount: 3,
    status: 'confirmed',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'bk-4',
    orgId: 'org-spacesync-hq',
    resourceId: 'res-1',
    resourceName: 'Boardroom Alpha',
    resourceType: 'room',
    building: 'Tower A, 4th Floor',
    requesterId: 'usr-2',
    requesterName: 'Sarah Jenkins',
    requesterEmail: 's.jenkins@spacesync.io',
    department: 'Marketing',
    title: 'Marketing Strategy Sync',
    startTime: `${todayStr}T09:00:00.000Z`,
    endTime: `${todayStr}T10:00:00.000Z`,
    attendeesCount: 10,
    status: 'confirmed',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'bk-5',
    orgId: 'org-spacesync-hq',
    resourceId: 'res-3',
    resourceName: 'Quiet Pod #4',
    resourceType: 'desk',
    building: 'North Hub, L2',
    requesterId: 'usr-1',
    requesterName: 'Michael R.',
    requesterEmail: 'm.r@spacesync.io',
    department: 'Engineering',
    title: 'Deep Work Session',
    startTime: `${todayStr}T11:00:00.000Z`,
    endTime: `${todayStr}T12:30:00.000Z`,
    attendeesCount: 1,
    status: 'checked_in',
    checkedInAt: `${todayStr}T11:02:00.000Z`,
    createdAt: new Date().toISOString(),
  },
];

export const initialApprovals: ApprovalRequest[] = [
  {
    id: 'appr-1',
    orgId: 'org-spacesync-hq',
    bookingId: 'bk-101',
    requesterName: 'Sarah Chen',
    requesterEmail: 's.chen@spacesync.io',
    department: 'Engineering',
    resourceName: 'Conf Room 402',
    resourceId: 'res-1',
    requestedTime: 'Oct 24, 14:00 - 16:30',
    startTime: `${todayStr}T14:00:00.000Z`,
    endTime: `${todayStr}T16:30:00.000Z`,
    priority: 'high',
    status: 'pending',
    createdAt: new Date(Date.now() - 120000).toISOString(),
  },
  {
    id: 'appr-2',
    orgId: 'org-spacesync-hq',
    bookingId: 'bk-102',
    requesterName: 'Marcus Thompson',
    requesterEmail: 'm.thompson@spacesync.io',
    department: 'Marketing',
    resourceName: 'Focus Pod A',
    resourceId: 'res-3',
    requestedTime: 'Oct 24, 09:00 - 12:00',
    startTime: `${todayStr}T09:00:00.000Z`,
    endTime: `${todayStr}T12:00:00.000Z`,
    priority: 'medium',
    status: 'pending',
    createdAt: new Date(Date.now() - 900000).toISOString(),
  },
  {
    id: 'appr-3',
    orgId: 'org-spacesync-hq',
    bookingId: 'bk-103',
    requesterName: 'Elena Rodriguez',
    requesterEmail: 'e.rod@spacesync.io',
    department: 'Legal',
    resourceName: 'Boardroom 01',
    resourceId: 'res-4',
    requestedTime: 'Oct 25, 10:00 - 15:00',
    startTime: `${todayStr}T10:00:00.000Z`,
    endTime: `${todayStr}T15:00:00.000Z`,
    priority: 'high',
    status: 'pending',
    createdAt: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: 'appr-4',
    orgId: 'org-spacesync-hq',
    bookingId: 'bk-104',
    requesterName: 'Alex Rivera',
    requesterEmail: 'a.rivera@spacesync.io',
    department: 'Product Design',
    resourceName: 'Design Lab 2',
    resourceId: 'res-6',
    requestedTime: 'Oct 26, 11:00 - 13:00',
    startTime: `${todayStr}T11:00:00.000Z`,
    endTime: `${todayStr}T13:00:00.000Z`,
    priority: 'low',
    status: 'pending',
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
];

export const initialNotifications: AppNotification[] = [
  {
    id: 'notif-1',
    orgId: 'org-spacesync-hq',
    userId: 'usr-1',
    title: 'System Update Completed',
    message: 'v2.41 deployed to all terminal nodes successfully.',
    type: 'booking_confirmed',
    read: false,
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'notif-2',
    orgId: 'org-spacesync-hq',
    userId: 'usr-1',
    title: 'New Resource Added',
    message: "'Level 4 Maker Space' is now live for bookings.",
    type: 'approval_request',
    read: false,
    createdAt: new Date(Date.now() - 18000000).toISOString(),
  },
  {
    id: 'notif-3',
    orgId: 'org-spacesync-hq',
    userId: 'usr-1',
    title: 'Check-In Reminder',
    message: 'Your booking for Meeting Room Alpha starts in 10 minutes.',
    type: 'reminder_10m',
    read: true,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
];
